export let customerArray = [
    {
      customerID: 1,
      img: "../assets/images/man.png",
      firstName: "Saman",
      lastName: "Silva",
      occupation: "Software Engineer",
      gender: "Male",
      location: "Kandy",
      email: "saman@gmail.com",
      phoneNumber: "0776775195",
      additionalInfo: "",
    },
    {
      customerID: 2,
      img: "../assets/images/man.png",
      firstName: "Anura",
      lastName: "Perera",
      occupation: "Teacher",
      gender: "Male",
      location: "Colombo",
      email: "anura@gmail.com",
      phoneNumber: "0771234567",
      additionalInfo: "",
    },
    {
      customerID: 3,
      img: "../assets/images/girl.png",
      firstName: "Kumari",
      lastName: "Wijesinghe",
      occupation: "Doctor",
      gender: "Female",
      location: "Galle",
      email: "kumari.w@gmail.com",
      phoneNumber: "0779234561",
      additionalInfo: "",
    },
    {
      customerID: 4,
      img: "../assets/images/man.png",
      firstName: "Sarath",
      lastName: "Fernando",
      occupation: "Accountant",
      gender: "Male",
      location: "Negombo",
      email: "sarathf@gmail.com",
      phoneNumber: "0711123456",
      additionalInfo: "",
    },
    {
      customerID: 5,
      img: "../assets/images/girl.png",
      firstName: "Nadeesha",
      lastName: "Bandara",
      occupation: "Engineer",
      gender: "Female",
      location: "Kurunegala",
      email: "nadeesha.b@gmail.com",
      phoneNumber: "0784567890",
      additionalInfo: "",
    },
    {
      customerID: 6,
      img: "../assets/images/man.png",
      firstName: "Mahinda",
      lastName: "Ranasinghe",
      occupation: "Lawyer",
      gender: "Male",
      location: "Jaffna",
      email: "mahinda.r@gmail.com",
      phoneNumber: "0763456789",
      additionalInfo: "",
    },
    {
      customerID: 7,
      img: "../assets/images/girl.png",
      firstName: "Sanduni",
      lastName: "Jayasinghe",
      occupation: "Pharmacist",
      gender: "Female",
      location: "Matara",
      email: "sanduni.j@gmail.com",
      phoneNumber: "0745678910",
      additionalInfo: "",
    },
    {
      customerID: 8,
      img: "../assets/images/girl.png",
      firstName: "Chathurika",
      lastName: "Gunasekara",
      occupation: "Architect",
      gender: "Female",
      location: "Ratnapura",
      email: "chathurika.g@gmail.com",
      phoneNumber: "0713456789",
      additionalInfo: "",
    },
    {
      customerID: 9,
      img: "../assets/images/man.png",
      firstName: "Ruwan",
      lastName: "Dias",
      occupation: "Chef",
      gender: "Male",
      location: "Kalutara",
      email: "ruwan.d@gmail.com",
      phoneNumber: "0729876543",
      additionalInfo: "",
    },
    {
      customerID: 10,
      img: "../assets/images/man.png",
      firstName: "Tharindu",
      lastName: "Rajapaksha",
      occupation: "Graphic Designer",
      gender: "Male",
      location: "Gampaha",
      email: "tharindu.r@gmail.com",
      phoneNumber: "0775566778",
      additionalInfo: "",
    },
  ];
